
openapi: 3.0.1
info:
  title: Credit Products API
  description: API para la gestión de productos de crédito en el banco
  version: 1.0.0

paths:
  /credits:
    get:
      summary: Obtener todos los créditos
      operationId: getAllCredits
      tags:
        - credit
      responses:
        '200':
          description: Lista de créditos
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Credit'
    post:
      summary: Crear un nuevo crédito
      operationId: createCredit
      tags:
        - credit
      responses:
        '201':
          description: Crédito creado exitosamente
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Credit'

  /credits/{id}:
    get:
      summary: Obtener un crédito por ID
      operationId: getCreditById
      tags:
        - credit
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Detalle del crédito
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Credit'
    put:
      summary: Actualizar un crédito
      operationId: updateCredit
      tags:
        - credit
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Crédito actualizado exitosamente
    delete:
      summary: Eliminar un crédito
      operationId: deleteCredit
      tags:
        - credit
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Crédito eliminado exitosamente

  /creditcards:
    get:
      summary: Obtener todas las tarjetas de crédito
      operationId: getAllCreditCards
      tags:
        - credicard
      responses:
        '200':
          description: Lista de tarjetas de crédito
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/CreditCard'
    post:
      summary: Crear una nueva tarjeta de crédito
      operationId: createCreditCard
      tags:
        - credicard
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreditCard'
      responses:
        '201':
          description: Tarjeta de crédito creada exitosamente
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreditCard'

  /creditcards/{id}:
    get:
      summary: Obtener una tarjeta de crédito por ID
      operationId: getCreditCardById
      tags:
        - credicard
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Detalle de la tarjeta de crédito
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreditCard'
    put:
      summary: Actualizar una tarjeta de crédito
      operationId: updateCreditCard
      tags:
        - credicard
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Tarjeta de crédito actualizada exitosamente
    delete:
      summary: Eliminar una tarjeta de crédito
      operationId: deleteCreditCard
      tags:
        - credicard
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Tarjeta de crédito eliminada exitosamente
    post:
      summary: Actualizar una tarjeta de crédito existente
      operationId: updateCreditCardDetails
      tags:
        - credicard
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreditCard'
      responses:
        '200':
          description: Tarjeta de crédito actualizada exitosamente
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreditCard'
  /creditcards/exists:
    post:
      summary: validate if you have a credit card
      operationId: hascreeditcard
      tags:
        - credicard
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/cardRequest'
      responses:
        '200':
          description: if you find an associated credit card
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/cardResponse'
        '404':
          description: Credit card not found

  /creditcards/{customerId}:
    get:
      summary: Obtener una tarjeta de crédito por ID
      operationId: getCreditCardOperation
      tags:
        - credicard
      parameters:
        - name: customerId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: list of transactions
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Transaction'

  /api/consume:
    post:
      summary: Consume a specified amount on the credit card
      operationId: consumeCreditCard
      tags:
        - consume
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/transactionRequest'  # Referencia al esquema de Transaction
      responses:
        '200':
          description: Credit card successfully updated with consumption
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Transaction'  # El esquema actualizado de la tarjeta de crédito
        '400':
          description: Insufficient credit limit or invalid request
        '404':
          description: Credit card not found


  /payments:
    post:
      summary: Registrar un pago de crédito
      operationId: registerPayment
      tags:
        - payments
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Payment'
      responses:
        '201':
          description: Pago registrado exitosamente
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Payment'

  /report/operations:
    post:
      operationId: reportOperations
      tags:
        - report
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ReportOperationsRequest"
      responses:
        '200':
          description: Single account operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ReportOperationsResponse"


components:
  schemas:
    Credit:
      type: object
      properties:
        id:
          type: string
        customerId:
          type: string
        creditType:
          type: string
          enum: [PERSONAL, EMPRESARIAL]
        amount:
          type: number
        interestRate:
          type: number
        termMonths:
          type: integer
        status:
          type: string
          enum: [ACTIVE, CLOSED]

    CreditCard:
      type: object
      properties:
        id:
          type: string
        customerId:
          type: string
        dni:
          type: string
        cardNumber:
          type: string
        expirationDate:
          type: string
          format: date
        limit:
          type: number
        balance:
          type: number
        status:
          type: string
          enum: [ACTIVE, BLOCKED, CLOSED]
        limitTransaction:
          type: number
          format: double

    Payment:
      type: object
      properties:
        id:
          type: string
        creditId:
          type: string
        amount:
          type: number
        paymentDate:
          type: string
          format: date
        customerId:
          type: string

        creditCards:
          type: array
          items:
            type: object
            properties:
              creditCardId:
                type: string
              availableBalance:
                type: number

    transactionRequest:
      type: object
      properties:
        customerId:
          type: string
        monto:
          type: number
        transactionType:
          type: string
          enum:
            - COMPRA
            - PAGO


    Transaction:
      type: object
      properties:
        dni:
          type: string
        customerId:
          type: string
        amount:
          type: number
          format: double
        transactionDate:
          type: string
          format: date
        transactionType:
          type: string
          enum:
            - Compra
            - Pago
      required:
        - customerId
        - amount
        - transactionDate
        - transactionType

    cardRequest:
      type: object
      properties:
        customerId:
          type: array
          items:
            type: string

    cardResponse:
      type: object
      properties:
        creditCard:
          type: boolean

    ReportOperationsResponse:
      type: object
      properties:
        dni:
          type: string
        amount:
          type: number
          format: double
        reportDate:
          type: string
          format: date

    ReportOperationsRequest:
      type: object
      properties:
        dni:
          type: string