/*
 * Yanki Wallet Service
 * API para el registro y operaciones del monedero móvil Yanki
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.nttdata.creditproducts.service.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.Objects;
import java.util.StringJoiner;


/**
 * AssociateCardRequest
 */
@JsonPropertyOrder({
  AssociateCardRequest.JSON_PROPERTY_DNI,
  AssociateCardRequest.JSON_PROPERTY_CARD_NUMBER
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen",
        date = "2025-04-18T22:39:48.098061700-05:00[America/Lima]")
public class AssociateCardRequest {
  public static final String JSON_PROPERTY_DNI = "dni";
  private String dni;

  public static final String JSON_PROPERTY_CARD_NUMBER = "cardNumber";
  private String cardNumber;

  public AssociateCardRequest() { 
  }

  public AssociateCardRequest dni(String dni) {
    this.dni = dni;
    return this;
  }

   /**
   * Get dni
   * @return dni
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DNI)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getDni() {
    return dni;
  }


  @JsonProperty(JSON_PROPERTY_DNI)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDni(String dni) {
    this.dni = dni;
  }


  public AssociateCardRequest cardNumber(String cardNumber) {
    this.cardNumber = cardNumber;
    return this;
  }

   /**
   * Get cardNumber
   * @return cardNumber
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CARD_NUMBER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getCardNumber() {
    return cardNumber;
  }


  @JsonProperty(JSON_PROPERTY_CARD_NUMBER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCardNumber(String cardNumber) {
    this.cardNumber = cardNumber;
  }


  /**
   * Return true if this AssociateCardRequest object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AssociateCardRequest associateCardRequest = (AssociateCardRequest) o;
    return Objects.equals(this.dni, associateCardRequest.dni) &&
        Objects.equals(this.cardNumber, associateCardRequest.cardNumber);
  }

  @Override
  public int hashCode() {
    return Objects.hash(dni, cardNumber);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AssociateCardRequest {\n");
    sb.append("    dni: ").append(toIndentedString(dni)).append("\n");
    sb.append("    cardNumber: ").append(toIndentedString(cardNumber)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `dni` to the URL query string
    if (getDni() != null) {
      joiner.add(String.format("%sdni%s=%s", prefix, suffix,
              URLEncoder.encode(String.valueOf(getDni()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `cardNumber` to the URL query string
    if (getCardNumber() != null) {
      joiner.add(String.format("%scardNumber%s=%s", prefix, suffix,
              URLEncoder.encode(String.valueOf(getCardNumber()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    return joiner.toString();
  }
}

